### ISSUE TITLE
Support user-provided origin location

### ISSUE THREAD

**Issue by DepthDeluxe** [maaaaaaaax/cvs-covid-vaccine-distances#2]
It appears there is a hard-coded origin address at https://github.com/maaaaaaaax/cvs-covid-vaccine-distances/blob/main/distance-calculator.js#L13.

Is it possible to make the origin a row somewhere in the source dataset?  Maybe you can provide a source sheets template with all the proper locations.

**Comment by maaaaaaaax** [comment]
Good catch! My assumption was that a user who could figure out how to create a filter view would also be able to understand step 7 of the readme, so for now I'm going to leave this as is.
